### ISSUE TITLE
How do you build this and where does it work?

### ISSUE THREAD

**Issue by mjobuda** [hylang/hyrule#13]
Docs in Hy and hyrule are misleading:
"just import hyrule". No, that does not make sense, there is no module with that name, it is also not distributed with Hy, it's not available in pip. It was not possible to "just import hyrule" as stated in a few places.
The only place I could get hyrules was this repository, but I was not able to get it running.
Is there any proven constellation or way to get it working?
![image](https://user-images.githubusercontent.com/14003621/132126087-42329220-b78a-47d2-8fe8-97fcbd86150b.png)

**Comment by Kodiologist** [comment]
This is the issues list. For support, ask on Stack Overflow or https://github.com/hylang/hy/discussions.

**Comment by mjobuda** [comment]
This is definitive in issue with documentation. "Just import hyrules" does not work when the user has Hy installed as described. And also as the screenshot shows it did not work at all on my system, crashing. I suspect it is due to a bug or some version incompatibilities.  Of course i can repost this in the discussion forum in order to not have the problem solved there. Really, stuff like that should work out if the box without the necessity to ask. Of course it's an issue :)))

**Comment by Kodiologist** [comment]
Correct me if I'm wrong, but I think your situation is:

1. You're upset that the Hy manual doesn't tell you to install Hyrule. I think this would be unnecessary considering that Hyrule is referred to by hyperlink, and the links leads to a different Git repository, implying a different Python package. Furthermore, after the first release of Hyrule, such links can be retargeted to PyPI, making Hyrule's identity as a different package yet more obvious. If you still think material should be added to the Hy manual spelling this out, you should post an issue against Hy, not Hyrule.
2. You can't get Hyrule to run, because you're using a released version of Hy with it, although you're looking at the manual for Hy `master`. Previous versions of Hy, which aren't supported by Hyrule, don't mention it in their manuals.

That's why it doesn't look to me like you have any documentation issues or bugs to report with respect to Hyrule.

**Comment by mjobuda** [comment]
1) I'm not upset.
2) do you mean that everything should work if both Hy and Hyrule were from master?
I used Hy stable, alpha and from master, i read sometimes this manual, sometimes that. The term documentation issue is very broad. As broad as democracy, if you ask me. Of course i don't know whether the issue is with Hy, Hyrule, the documentation or my stupidity. Or an .install issue

**Comment by Kodiologist** [comment]
> do you mean that everything should work if both Hy and Hyrule were from master?

Yes.
