### ISSUE TITLE
Fix various documentation bugs

### ISSUE THREAD

**Issue by scauligi** [hylang/hyrule#71]
Currently, building the sphinx docs kicks up a bunch of warnings.

Things I've noticed:

Hy example code containing the ellipsis symbol `…` instead of three dots `...` fails to parse for syntax highlighting, although this could also be treated as a bug in pygments' `HyLexer`.

`.. code-block:: hy` is [wrong](https://pygments.org/languages/), as that abbreviation was unfortunately stolen by Hybris.
In any case, `.. code-block:: hylang` is redundant after #70.

There are also a few different scattered broken refs, and there might be other stuff I haven't listed here. The docs in general could probably use a solid once-over.

**Comment by Kodiologist** [comment]
> although this could also be treated as a bug in pygments' `HyLexer`

It is. As I understand, pygments has a longstanding bug regarding non-ASCII characters. I've never looked into it deeply.

**Comment by Kodiologist** [comment]
> `.. code-block:: hy` is [wrong](https://pygments.org/languages/), as that abbreviation was unfortunately stolen by Hybris.

I think we should be able to make a decent case to the pygments people to rename ours to `hy` considering that Hybris is long dead. I can't even find the repository anymore.

**Comment by atisharma** [comment]
`ncut` is also missing.

**Comment by Kodiologist** [comment]
I forgot this issue existed, but all the specific problems listed here were addressed by some cleanup that I did a while ago. It's still fair to say that "The docs in general could probably use a solid once-over" because I haven't rewritten documentation for things that I suspect I may change or remove in the future. I can fuss over that documentation once I'm sure about what's being documented.
